# Generated by Django 4.2.6 on 2024-07-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_per',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='mrp_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
